### ISSUE TITLE
not fund json files keys 

### ISSUE THREAD

**Issue by lmottasin** [AriesAlex/ariex-custom-tabpage#1]
![image](https://github.com/AriesAlex/ariex-custom-tabpage/assets/68915904/a22aebf4-9f27-43d6-9132-c01666428a0f)

**Comment by lmottasin** [comment]
got it need to set the the lazy load to false. [see](https://github.com/nuxt-modules/i18n/issues/2044)

**Comment by AriesAlex** [comment]
can you please explain more? in linked issue error was caused when overriding language for t. but i dont use that for this project. for adding new language you need to add it to locales.ts and create a new json in locales/... .json

**Comment by AriesAlex** [comment]
oh, i actually do use it for server middleware
but still strange i didnt have that error

**Comment by lmottasin** [comment]
![image](https://github.com/AriesAlex/ariex-custom-tabpage/assets/68915904/20f9fa6f-2ad6-4f7e-8c2e-35e16f2f32c1)
do you have any idea why my composable file not working

**Comment by AriesAlex** [comment]
need to see the code but error is pretty self-explaining - you probably called composable from context that dont have nuxt instance

**Comment by AriesAlex** [comment]
anyway, this is off topic, so I will close the issue
